image: python:3.11-slim

stages:
  - test

test:
  image: python:3.11-slim
  before_script:
    - apt-get update
    - apt-get install -y --no-install-recommends libglib2.0-0 libgl1 libxkbcommon0 libdbus-1-3 libx11-6 libxext6 libxcb1 libxi6 libxrender1 libxrandr2 libxfixes3 libegl1 libopengl0 libfontconfig1
  script:
    - pip install .[dev]
    - pytest -q
