image: python:3.11-slim

stages:
  - test

test:
  image: python:3.11-slim
  before_script:
    - apt-get update
    - apt-get install -y --no-install-recommends libglib2.0-0
  script:
    - pip install .[dev]
    - pytest -q
